version: "2.0"
services:
  ng-blackbox:
    build:
      context: ng-blackbox/.
    ports:
      - "8081:80"
    volumes:
      - ./ng-blackbox/nginx/:/etc/nginx/conf.d/
  py-blackbox:
    build:
      context: py_blackbox_backend/.
    ports:
      - "8082:8000"