# Generated by Django 3.1.7 on 2021-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='group',
            field=models.CharField(default='gt', max_length=10),
            preserve_default=False,
        ),
    ]
