# Generated by Django 3.1.7 on 2021-03-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('car', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('circuit', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='circuit.circuit')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.IntegerField()),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
    ]
