# Generated by Django 3.1.7 on 2021-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20210315_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='session_id',
        ),
        migrations.AddField(
            model_name='lap',
            name='fuel_used',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
        migrations.AddField(
            model_name='lap',
            name='stint_id',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='session.stint'),
            preserve_default=False,
        ),
    ]
