# Generated by Django 3.1.7 on 2021-03-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20210315_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='delta_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='is_valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
