# Generated by Django 3.1.7 on 2021-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20210316_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='sector1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='sector2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='sector3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
