# Generated by Django 3.1.7 on 2021-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20210319_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='sector1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='sector2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='sector3',
            field=models.IntegerField(null=True),
        ),
    ]
