# Generated by Django 3.1.7 on 2021-03-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_type', '0001_initial'),
        ('session', '0007_auto_20210319_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='session_type.sessiontype'),
            preserve_default=False,
        ),
    ]
