# Generated by Django 3.1.7 on 2021-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210331_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='front_left_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='front_right_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='rear_left_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='rear_right_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='air_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='track_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
