# Generated by Django 3.1.7 on 2021-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20210503_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='air_temp',
        ),
        migrations.RemoveField(
            model_name='session',
            name='track_temp',
        ),
        migrations.AddField(
            model_name='lap',
            name='air_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='track_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
